"""Attack-first feasibility probe for a Burau-switch security device.

This experiment treats a short braid word as a hidden device parameter and
asks how many scalar T--S challenge responses are needed to identify its
response class by exhaustive model matching.  It is a deliberately favorable
test for an attacker, not a claim of cryptographic security.
"""

from __future__ import annotations

import itertools
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np
import numpy.linalg as la
import sympy as sp

from burau_switch import (
    beta_generator,
    definiteness_sign,
    helstrom_unitary_success,
    positive_form,
    positive_square_root,
    rx,
    rz,
    switch_unitary,
)


HERE = Path(__file__).resolve().parent
FIGURE_PATH = HERE / "figures" / "security_probe.png"
RESULTS_PATH = HERE / "results" / "security_probe.json"
LETTERS = (-2, -1, 1, 2)
TARGET_WORD = (1, 2, -1, 2, 1)


def _letter_matrix(letter: int, s: complex) -> np.ndarray:
    generator = beta_generator(abs(letter), s)
    return generator if letter > 0 else la.inv(generator)


def _reverse_word(word: tuple[int, ...]) -> tuple[int, ...]:
    """Reverse application order without changing the signed letters."""
    return tuple(reversed(word))


def _tau_inverse_word(word: tuple[int, ...]) -> tuple[int, ...]:
    """Return tau(w^-1), where tau exchanges generator indices 1 and 2."""
    return tuple(
        (-1 if letter > 0 else 1) * (3 - abs(letter))
        for letter in reversed(word)
    )


def _symmetry_orbit(word: tuple[int, ...]) -> frozenset[tuple[int, ...]]:
    """Orbit generated by reversal and tau-after-inversion."""
    tau_inverse = _tau_inverse_word(word)
    return frozenset(
        (word, _reverse_word(word), tau_inverse, _reverse_word(tau_inverse))
    )


def _burnside_orbit_audit(maximum_word_length: int = 6) -> list[dict[str, int]]:
    """Check the exact Klein-four orbit count for signed words."""
    audit = []
    for word_length in range(1, maximum_word_length + 1):
        raw_words = 4**word_length
        fixed_by_reversal = 4 ** ((word_length + 1) // 2)
        fixed_by_tau_inverse = (
            4 ** (word_length // 2) if word_length % 2 == 0 else 0
        )
        # The remaining nonidentity element applies a fixed-point-free signed
        # letter involution independently at every position.
        fixed_by_composition = 0
        burnside_bound = (
            raw_words
            + fixed_by_reversal
            + fixed_by_tau_inverse
            + fixed_by_composition
        ) // 4

        words = itertools.product(LETTERS, repeat=word_length)
        enumerated_orbits = {
            min(_symmetry_orbit(word))
            for word in words
        }
        assert len(enumerated_orbits) == burnside_bound
        audit.append(
            {
                "word_length": word_length,
                "raw_signed_words": raw_words,
                "fixed_by_identity": raw_words,
                "fixed_by_reversal": fixed_by_reversal,
                "fixed_by_tau_after_inverse": fixed_by_tau_inverse,
                "fixed_by_nonidentity_composition": fixed_by_composition,
                "burnside_response_orbit_upper_bound": burnside_bound,
                "enumerated_symmetry_orbits": len(enumerated_orbits),
            }
        )
    return audit


def _symbolic_symmetry_checks() -> dict[str, str]:
    """Verify the algebra behind the projective-spectrum collision theorem."""
    s = sp.symbols("s", nonzero=True)
    a, b = sp.symbols("a b")
    epsilon = sp.symbols("epsilon", nonzero=True)
    root = sp.Matrix([[a, b], [b, a]])
    beta_one = sp.Matrix([[-s**2, s], [0, 1]])
    beta_two = sp.Matrix([[1, 0], [s, -s**2]])
    exchange = sp.Matrix([[0, 1], [1, 0]])
    assert sp.simplify(beta_two - exchange * beta_one * exchange) == sp.zeros(2)

    unitary_one = sp.simplify(root * beta_one * root.inv())
    transpose_numerator = sp.factor(
        (unitary_one[0, 1] - unitary_one[1, 0]) * root.det()
    )
    expected_numerator = sp.expand(
        (a**2 + b**2) * s + 2 * a * b * (1 + s**2)
    )
    assert sp.simplify(transpose_numerator - expected_numerator) == 0
    reduced_numerator = sp.expand(
        epsilon * (s + s**-1) * s - epsilon * (1 + s**2)
    )
    assert sp.simplify(reduced_numerator) == 0

    alpha, beta, gamma, delta = sp.symbols(
        "alpha beta gamma delta", nonzero=True
    )
    first_block, second_block = sp.symbols("A B")
    mixer = sp.Matrix([[alpha, beta], [gamma, delta]])
    switch = sp.diag(first_block, second_block)
    scaling = sp.diag(beta / gamma, 1)
    dressed = sp.expand(mixer * switch * mixer)
    transposed_dressed = sp.expand(mixer.T * switch * mixer.T)
    assert sp.simplify(scaling.inv() * dressed * scaling - transposed_dressed) == (
        sp.zeros(2)
    )

    phase_flip = sp.diag(1, -1)
    inverse_exchange = sp.simplify(exchange * mixer.inv() * exchange)
    projective_transpose = sp.simplify(
        phase_flip * mixer.T * phase_flip / mixer.det()
    )
    assert sp.simplify(inverse_exchange - projective_transpose) == sp.zeros(2)

    return {
        "generator_exchange": "beta_2 = P beta_1 P",
        "unitarized_generator_transpose": (
            "U_i^T = U_i from C^2 = epsilon J and 1+s^2=(s+s^-1)s"
        ),
        "same_sided_transpose_similarity": (
            "D_S(M^T) = T^-1 D_S(M) T for block-diagonal S"
        ),
        "tau_inverse_projective_conjugacy": (
            "P M^-1 P = det(M)^-1 Z M^T Z"
        ),
    }


def _generator_symmetry_diagnostics(omegas: np.ndarray) -> dict[str, float]:
    """Measure the generator identities used by the exact proof."""
    exchange = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex)
    maximum_transpose_residual = 0.0
    maximum_exchange_residual = 0.0
    for omega in omegas:
        s = np.exp(0.5j * omega)
        root = positive_square_root(positive_form(float(omega)))
        inverse_root = la.inv(root)
        generators = {
            index: root @ beta_generator(index, s) @ inverse_root
            for index in (1, 2)
        }
        signed_generators = tuple(generators.values()) + tuple(
            la.inv(generator) for generator in generators.values()
        )
        maximum_transpose_residual = max(
            maximum_transpose_residual,
            max(
                float(la.norm(generator - generator.T))
                for generator in signed_generators
            ),
        )
        maximum_exchange_residual = max(
            maximum_exchange_residual,
            float(la.norm(generators[2] - exchange @ generators[1] @ exchange)),
        )
    return {
        "maximum_signed_generator_transpose_residual": (
            maximum_transpose_residual
        ),
        "maximum_generator_exchange_residual": maximum_exchange_residual,
    }


def _response_library(
    words: list[tuple[int, ...]], omegas: np.ndarray
) -> np.ndarray:
    """Return the braid-dressed-minus-bare response for every word/challenge."""
    first_target = rx(1.5)
    second_target = rz(0.75)
    identity_two = np.eye(2, dtype=complex)
    identity_four = np.eye(4, dtype=complex)
    responses = np.empty((len(words), len(omegas)), dtype=float)

    for challenge_index, omega in enumerate(omegas):
        if definiteness_sign(float(omega)) is None:
            raise ValueError("all challenge phases must lie in Omega_+")

        s = np.exp(0.5j * omega)
        form = positive_form(float(omega))
        root = positive_square_root(form)
        inverse_root = la.inv(root)
        letter_matrices = {
            letter: _letter_matrix(letter, s) for letter in LETTERS
        }
        bare_switch = switch_unitary(first_target, second_target, float(omega))
        bare_score = helstrom_unitary_success(identity_four, bare_switch)

        for word_index, word in enumerate(words):
            raw_word = identity_two
            for letter in word:
                raw_word = raw_word @ letter_matrices[letter]
            mixer = root @ raw_word @ inverse_root
            lifted_mixer = np.kron(mixer, identity_two)
            dressed_switch = lifted_mixer @ bare_switch @ lifted_mixer
            responses[word_index, challenge_index] = (
                helstrom_unitary_success(identity_four, dressed_switch)
                - bare_score
            )

    return responses


def _deduplicate_response_classes(
    words: list[tuple[int, ...]], responses: np.ndarray
) -> tuple[list[tuple[int, ...]], np.ndarray, np.ndarray]:
    """Collapse words whose complete sampled response curves coincide."""
    fingerprints = np.round(responses, decimals=11)
    _, first_indices, inverse = np.unique(
        fingerprints, axis=0, return_index=True, return_inverse=True
    )
    order = np.argsort(first_indices)
    first_indices = first_indices[order]

    old_to_new = np.empty(len(order), dtype=int)
    old_to_new[order] = np.arange(len(order))
    remapped_inverse = old_to_new[inverse]
    unique_words = [words[index] for index in first_indices]
    return unique_words, responses[first_indices], remapped_inverse


def _probe_order(response_classes: np.ndarray) -> np.ndarray:
    """Greedily choose diverse challenges by pivoted residual variance."""
    residual = response_classes - np.mean(response_classes, axis=0, keepdims=True)
    remaining = list(range(response_classes.shape[1]))
    selected: list[int] = []
    while remaining:
        scores = np.sum(residual[:, remaining] ** 2, axis=0)
        best_position = int(np.argmax(scores))
        best = remaining.pop(best_position)
        selected.append(best)
        direction = residual[:, best]
        norm_squared = float(direction @ direction)
        if norm_squared > 1e-24:
            residual -= np.outer(direction, direction @ residual) / norm_squared
    return np.asarray(selected, dtype=int)


def _matching_attack(
    response_classes: np.ndarray,
    probe_order: np.ndarray,
    probe_counts: list[int],
    noise_standard_deviation: float,
    trials: int,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Average model matching over uniformly sampled hidden response classes."""
    rng = np.random.default_rng(seed)
    success_rates = np.empty(len(probe_counts), dtype=float)
    prediction_errors = np.empty(len(probe_counts), dtype=float)

    for count_index, count in enumerate(probe_counts):
        selected = probe_order[:count]
        successes = 0
        trial_errors = []
        for _ in range(trials):
            target_class = int(rng.integers(len(response_classes)))
            target = response_classes[target_class]
            observed = target[selected] + rng.normal(
                scale=noise_standard_deviation, size=count
            )
            squared_errors = np.mean(
                (response_classes[:, selected] - observed) ** 2, axis=1
            )
            predicted_class = int(np.argmin(squared_errors))
            successes += int(predicted_class == target_class)
            trial_errors.append(
                float(
                    np.sqrt(
                        np.mean((response_classes[predicted_class] - target) ** 2)
                    )
                )
            )
        success_rates[count_index] = successes / trials
        prediction_errors[count_index] = float(np.mean(trial_errors))

    return success_rates, prediction_errors


def _wilson_interval(
    success_rate: float, trials: int, z_score: float = 1.959963984540054
) -> tuple[float, float]:
    """Return the two-sided Wilson score interval for a binomial rate."""
    denominator = 1.0 + z_score**2 / trials
    center = (success_rate + z_score**2 / (2.0 * trials)) / denominator
    radius = (
        z_score
        / denominator
        * np.sqrt(
            success_rate * (1.0 - success_rate) / trials
            + z_score**2 / (4.0 * trials**2)
        )
    )
    return float(center - radius), float(center + radius)


def run_security_probe(
    *,
    word_length: int = 5,
    challenges_per_component: int = 36,
    noise_standard_deviations: tuple[float, ...] = (5e-4, 2e-3, 1e-2),
    trials: int = 1500,
    target_word: tuple[int, ...] = TARGET_WORD,
    seed: int = 1701,
) -> dict[str, object]:
    """Generate the response library, run the attack, and save diagnostics."""
    if len(target_word) != word_length or any(
        letter not in LETTERS for letter in target_word
    ):
        raise ValueError("target_word must contain word_length valid letters")
    if challenges_per_component < 1:
        raise ValueError("challenges_per_component must be positive")
    if not noise_standard_deviations or any(
        noise < 0.0 for noise in noise_standard_deviations
    ):
        raise ValueError("noise_standard_deviations must be nonempty and nonnegative")
    if trials < 1:
        raise ValueError("trials must be positive")

    margin = 0.06
    left = np.linspace(
        margin, 2.0 * np.pi / 3.0 - margin, challenges_per_component
    )
    right = np.linspace(
        4.0 * np.pi / 3.0 + margin,
        2.0 * np.pi - margin,
        challenges_per_component,
    )
    omegas = np.concatenate((left, right))
    words = list(itertools.product(LETTERS, repeat=word_length))
    responses = _response_library(words, omegas)
    unique_words, response_classes, class_for_word = _deduplicate_response_classes(
        words, responses
    )

    target_word_index = words.index(target_word)
    target_class = int(class_for_word[target_word_index])
    order = _probe_order(response_classes)
    probe_counts = [
        count
        for count in (1, 2, 3, 4, 6, 8, 12, 16)
        if count <= len(omegas)
    ]
    attack_results: dict[str, dict[str, list[float]]] = {}
    for noise_index, noise_standard_deviation in enumerate(
        noise_standard_deviations
    ):
        success_rates, prediction_errors = _matching_attack(
            response_classes,
            order,
            probe_counts,
            noise_standard_deviation,
            trials,
            seed + 1 + noise_index,
        )
        attack_results[f"{noise_standard_deviation:.6g}"] = {
            "exact_class_recovery_rate": success_rates.tolist(),
            "exact_class_recovery_95_percent_wilson_interval": [
                list(_wilson_interval(float(rate), trials))
                for rate in success_rates
            ],
            "mean_full_curve_rmse": prediction_errors.tolist(),
            "mean_full_curve_rmse_over_noise": (
                (prediction_errors / noise_standard_deviation).tolist()
                if noise_standard_deviation > 0.0
                else [0.0 for _ in prediction_errors]
            ),
        }

    centered = response_classes - np.mean(response_classes, axis=0, keepdims=True)
    singular_values = la.svd(centered, compute_uv=False)
    explained = np.cumsum(singular_values**2) / np.sum(singular_values**2)
    dimensions_99 = int(np.searchsorted(explained, 0.99) + 1)
    dimensions_999 = int(np.searchsorted(explained, 0.999) + 1)
    class_sizes = np.bincount(class_for_word)
    raw_word_class_probabilities = class_sizes / len(words)
    raw_word_class_shannon_entropy = float(
        -np.sum(
            raw_word_class_probabilities
            * np.log2(raw_word_class_probabilities)
        )
    )
    raw_word_class_min_entropy = float(
        -np.log2(np.max(raw_word_class_probabilities))
    )

    inverse_letter = {1: -1, -1: 1, 2: -2, -2: 2}
    freely_reduced_indices = np.asarray(
        [
            index
            for index, word in enumerate(words)
            if all(
                word[position + 1] != inverse_letter[word[position]]
                for position in range(word_length - 1)
            )
        ],
        dtype=int,
    )
    freely_reduced_class_sizes = np.bincount(
        class_for_word[freely_reduced_indices], minlength=len(unique_words)
    )
    nonempty_freely_reduced_classes = freely_reduced_class_sizes[
        freely_reduced_class_sizes > 0
    ]
    freely_reduced_probabilities = (
        nonempty_freely_reduced_classes / len(freely_reduced_indices)
    )

    validation_rng = np.random.default_rng(seed + 20_000)
    validation_phases_per_component = 20
    validation_omegas = np.concatenate(
        (
            np.sort(
                validation_rng.uniform(
                    margin,
                    2.0 * np.pi / 3.0 - margin,
                    size=validation_phases_per_component,
                )
            ),
            np.sort(
                validation_rng.uniform(
                    4.0 * np.pi / 3.0 + margin,
                    2.0 * np.pi - margin,
                    size=validation_phases_per_component,
                )
            ),
        )
    )
    validation_responses = _response_library(words, validation_omegas)
    maximum_within_class_validation_spread = 0.0
    for class_index in range(len(unique_words)):
        members = np.flatnonzero(class_for_word == class_index)
        reference = validation_responses[members[0]]
        maximum_within_class_validation_spread = max(
            maximum_within_class_validation_spread,
            float(np.max(np.abs(validation_responses[members] - reference))),
        )

    word_to_index = {word: index for index, word in enumerate(words)}
    reversal_indices = np.asarray(
        [word_to_index[_reverse_word(word)] for word in words], dtype=int
    )
    tau_inverse_indices = np.asarray(
        [word_to_index[_tau_inverse_word(word)] for word in words], dtype=int
    )
    maximum_reversal_response_residual = float(
        np.max(np.abs(responses - responses[reversal_indices]))
    )
    maximum_tau_inverse_response_residual = float(
        np.max(np.abs(responses - responses[tau_inverse_indices]))
    )
    validation_reversal_response_residual = float(
        np.max(
            np.abs(validation_responses - validation_responses[reversal_indices])
        )
    )
    validation_tau_inverse_response_residual = float(
        np.max(
            np.abs(
                validation_responses - validation_responses[tau_inverse_indices]
            )
        )
    )
    generator_symmetry = _generator_symmetry_diagnostics(
        np.concatenate((omegas, validation_omegas))
    )
    symbolic_symmetry = _symbolic_symmetry_checks()
    orbit_audit = _burnside_orbit_audit(maximum_word_length=6)

    symmetry_tolerance = 1e-10
    assert maximum_reversal_response_residual < symmetry_tolerance
    assert maximum_tau_inverse_response_residual < symmetry_tolerance
    assert validation_reversal_response_residual < symmetry_tolerance
    assert validation_tau_inverse_response_residual < symmetry_tolerance
    assert (
        generator_symmetry["maximum_signed_generator_transpose_residual"]
        < symmetry_tolerance
    )
    assert (
        generator_symmetry["maximum_generator_exchange_residual"]
        < symmetry_tolerance
    )

    diagnostics: dict[str, object] = {
        "attack_model": "enumeration of all fixed-length braid words",
        "attack_target_sampling": "uniform over distinct response classes",
        "word_length": word_length,
        "seed": seed,
        "trials_per_attack_point": trials,
        "challenges_per_definiteness_component": challenges_per_component,
        "enumerated_words": len(words),
        "distinct_sampled_response_classes": len(unique_words),
        "sampled_response_class_capacity_bits": float(np.log2(len(unique_words))),
        "largest_equivalent_word_class": int(np.max(class_sizes)),
        "centered_response_matrix_numerical_rank": int(
            la.matrix_rank(centered, tol=1e-10)
        ),
        "raw_word_prior_class_shannon_entropy_bits": raw_word_class_shannon_entropy,
        "raw_word_prior_class_min_entropy_bits": raw_word_class_min_entropy,
        "freely_reduced_words": int(len(freely_reduced_indices)),
        "distinct_classes_among_freely_reduced_words": int(
            len(nonempty_freely_reduced_classes)
        ),
        "freely_reduced_word_prior_class_shannon_entropy_bits": float(
            -np.sum(
                freely_reduced_probabilities
                * np.log2(freely_reduced_probabilities)
            )
        ),
        "freely_reduced_word_prior_class_min_entropy_bits": float(
            -np.log2(np.max(freely_reduced_probabilities))
        ),
        "challenge_count": len(omegas),
        "challenge_phases": omegas.tolist(),
        "noise_standard_deviations": list(noise_standard_deviations),
        "challenge_selection": "pivoted residual variance",
        "selected_probe_indices": order[: probe_counts[-1]].tolist(),
        "selected_probe_phases": omegas[order[: probe_counts[-1]]].tolist(),
        "target_word": list(target_word),
        "target_response_class": target_class,
        "dimensions_for_99_percent_variance": dimensions_99,
        "dimensions_for_99_9_percent_variance": dimensions_999,
        "off_grid_equivalence_validation": {
            "seed": seed + 20_000,
            "phases_per_definiteness_component": validation_phases_per_component,
            "maximum_within_class_absolute_response_spread": (
                maximum_within_class_validation_spread
            ),
        },
        "same_sided_projective_spectrum_symmetry_audit": {
            "scope": (
                "same-sided dressing D_S(M)=(M tensor I) S (M tensor I), "
                "block-diagonal S, and responses depending only on the "
                "projective spectrum"
            ),
            "symbolic_checks": symbolic_symmetry,
            "generator_checks_on_main_and_validation_phases": generator_symmetry,
            "maximum_main_grid_reversal_response_residual": (
                maximum_reversal_response_residual
            ),
            "maximum_main_grid_tau_after_inverse_response_residual": (
                maximum_tau_inverse_response_residual
            ),
            "maximum_validation_grid_reversal_response_residual": (
                validation_reversal_response_residual
            ),
            "maximum_validation_grid_tau_after_inverse_response_residual": (
                validation_tau_inverse_response_residual
            ),
            "assertion_tolerance": symmetry_tolerance,
            "burnside_formula": (
                "(4^L + 4^ceil(L/2) + 1_{L even} 4^(L/2)) / 4"
            ),
            "orbit_counts": orbit_audit,
        },
        "probe_counts": probe_counts,
        "attack_results_by_noise": attack_results,
    }

    figure, axes = plt.subplots(1, 3, figsize=(13.2, 3.8))
    target_response = response_classes[target_class]
    sample_indices = np.linspace(
        0, len(response_classes) - 1, min(24, len(response_classes)), dtype=int
    )
    valid_segments = (
        slice(0, challenges_per_component),
        slice(challenges_per_component, None),
    )
    for index in sample_indices:
        for segment in valid_segments:
            axes[0].plot(
                omegas[segment],
                response_classes[index, segment],
                color="0.72",
                alpha=0.35,
            )
    for segment_index, segment in enumerate(valid_segments):
        axes[0].plot(
            omegas[segment],
            target_response[segment],
            color="#7f3c8d",
            linewidth=2.2,
            label="target response" if segment_index == 0 else None,
        )
    axes[0].axvspan(
        2.0 * np.pi / 3.0,
        4.0 * np.pi / 3.0,
        color="0.92",
        label="indefinite Squier form",
    )
    axes[0].set_xlim(0.0, 2.0 * np.pi)
    axes[0].set_xticks(
        [0.0, 2.0 * np.pi / 3.0, 4.0 * np.pi / 3.0, 2.0 * np.pi],
        [r"$0$", r"$2\pi/3$", r"$4\pi/3$", r"$2\pi$"],
    )
    axes[0].set_xlabel(r"challenge phase $\omega$")
    axes[0].set_ylabel(r"$\Delta_{\rm int}$")
    axes[0].set_title("(a) Enumerable response family")
    axes[0].legend(fontsize=8)

    normalized_singular_values = singular_values / singular_values[0]
    axes[1].semilogy(
        np.arange(1, len(normalized_singular_values) + 1),
        normalized_singular_values,
        marker="o",
        markersize=2.5,
        linewidth=1.1,
    )
    axes[1].axvline(dimensions_99, color="#d95f02", linestyle="--", label="99%")
    axes[1].axvline(
        dimensions_999, color="#1b9e77", linestyle=":", label="99.9%"
    )
    axes[1].set_xlabel("response-space component")
    axes[1].set_ylabel("normalized singular value")
    axes[1].set_title("(b) Response-space spectrum")
    axes[1].legend(fontsize=8)

    attack_colors = plt.cm.viridis(
        np.linspace(0.15, 0.85, len(noise_standard_deviations))
    )
    for color, noise_standard_deviation in zip(
        attack_colors, noise_standard_deviations, strict=True
    ):
        rates = attack_results[f"{noise_standard_deviation:.6g}"][
            "exact_class_recovery_rate"
        ]
        axes[2].plot(
            probe_counts,
            rates,
            color=color,
            marker="o",
            label=rf"noise $\sigma={noise_standard_deviation:g}$",
        )
    axes[2].set_xlabel("observed challenge responses")
    axes[2].set_ylabel("mean exact-class recovery")
    axes[2].set_ylim(-0.03, 1.03)
    axes[2].set_title("(c) Enumeration attack")
    axes[2].legend(fontsize=8)

    for axis in axes:
        axis.grid(alpha=0.2)
    figure.suptitle(
        "Current low-dimensional braid response is a model-extraction target",
        fontsize=12,
    )
    figure.tight_layout()
    FIGURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(FIGURE_PATH, dpi=220, bbox_inches="tight")
    plt.close(figure)

    RESULTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    RESULTS_PATH.write_text(
        json.dumps(diagnostics, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote {FIGURE_PATH.relative_to(Path.cwd())}")
    print(f"Wrote {RESULTS_PATH.relative_to(Path.cwd())}")
    print(json.dumps(diagnostics, indent=2, sort_keys=True))
    return diagnostics


if __name__ == "__main__":
    run_security_probe()
